/*
 * Kinetic Smart API
 * Kinetic Smart Swagger Implementatin
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.citypay.pos.api.kinetic;

import com.citypay.invoker.ApiException;
import com.citypay.pos.model.kinetic.BatteryResponse;
import com.citypay.pos.model.kinetic.PingResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeviceApi
 */
@Ignore
public class DeviceApiTest {

    private final DeviceApi api = new DeviceApi();


    
    /**
     * Simple function to detect the presence of the device on the network. Typically, only used for system setup validation and testing.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pingJsonGetTest() throws ApiException {
        PingResponse response = api.pingJsonGet();

        // TODO: test validations
    }
    
}
