/*
 * Kinetic Smart API
 * Kinetic Smart Swagger Implementatin
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.citypay.pos.model.kinetic;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InfoResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-19T12:47:05.325Z")
public class InfoResponse {
  @SerializedName("battery_charging")
  private Boolean batteryCharging = null;

  @SerializedName("battery_percentage")
  private Integer batteryPercentage = null;

  @SerializedName("busy")
  private Boolean busy = null;

  @SerializedName("connection_mode")
  private String connectionMode = null;

  @SerializedName("device")
  private String device = null;

  @SerializedName("portable")
  private Boolean portable = null;

  @SerializedName("printer")
  private Boolean printer = null;

  @SerializedName("serial")
  private String serial = null;

  @SerializedName("update_ready")
  private Boolean updateReady = null;

  public InfoResponse batteryCharging(Boolean batteryCharging) {
    this.batteryCharging = batteryCharging;
    return this;
  }

   /**
   * Get batteryCharging
   * @return batteryCharging
  **/
  @ApiModelProperty(value = "")
  public Boolean isBatteryCharging() {
    return batteryCharging;
  }

  public void setBatteryCharging(Boolean batteryCharging) {
    this.batteryCharging = batteryCharging;
  }

  public InfoResponse batteryPercentage(Integer batteryPercentage) {
    this.batteryPercentage = batteryPercentage;
    return this;
  }

   /**
   * Get batteryPercentage
   * @return batteryPercentage
  **/
  @ApiModelProperty(value = "")
  public Integer getBatteryPercentage() {
    return batteryPercentage;
  }

  public void setBatteryPercentage(Integer batteryPercentage) {
    this.batteryPercentage = batteryPercentage;
  }

  public InfoResponse busy(Boolean busy) {
    this.busy = busy;
    return this;
  }

   /**
   * Get busy
   * @return busy
  **/
  @ApiModelProperty(value = "")
  public Boolean isBusy() {
    return busy;
  }

  public void setBusy(Boolean busy) {
    this.busy = busy;
  }

  public InfoResponse connectionMode(String connectionMode) {
    this.connectionMode = connectionMode;
    return this;
  }

   /**
   * Get connectionMode
   * @return connectionMode
  **/
  @ApiModelProperty(value = "")
  public String getConnectionMode() {
    return connectionMode;
  }

  public void setConnectionMode(String connectionMode) {
    this.connectionMode = connectionMode;
  }

  public InfoResponse device(String device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @ApiModelProperty(value = "")
  public String getDevice() {
    return device;
  }

  public void setDevice(String device) {
    this.device = device;
  }

  public InfoResponse portable(Boolean portable) {
    this.portable = portable;
    return this;
  }

   /**
   * Get portable
   * @return portable
  **/
  @ApiModelProperty(value = "")
  public Boolean isPortable() {
    return portable;
  }

  public void setPortable(Boolean portable) {
    this.portable = portable;
  }

  public InfoResponse printer(Boolean printer) {
    this.printer = printer;
    return this;
  }

   /**
   * Get printer
   * @return printer
  **/
  @ApiModelProperty(value = "")
  public Boolean isPrinter() {
    return printer;
  }

  public void setPrinter(Boolean printer) {
    this.printer = printer;
  }

  public InfoResponse serial(String serial) {
    this.serial = serial;
    return this;
  }

   /**
   * Get serial
   * @return serial
  **/
  @ApiModelProperty(value = "")
  public String getSerial() {
    return serial;
  }

  public void setSerial(String serial) {
    this.serial = serial;
  }

  public InfoResponse updateReady(Boolean updateReady) {
    this.updateReady = updateReady;
    return this;
  }

   /**
   * Get updateReady
   * @return updateReady
  **/
  @ApiModelProperty(value = "")
  public Boolean isUpdateReady() {
    return updateReady;
  }

  public void setUpdateReady(Boolean updateReady) {
    this.updateReady = updateReady;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoResponse infoResponse = (InfoResponse) o;
    return Objects.equals(this.batteryCharging, infoResponse.batteryCharging) &&
        Objects.equals(this.batteryPercentage, infoResponse.batteryPercentage) &&
        Objects.equals(this.busy, infoResponse.busy) &&
        Objects.equals(this.connectionMode, infoResponse.connectionMode) &&
        Objects.equals(this.device, infoResponse.device) &&
        Objects.equals(this.portable, infoResponse.portable) &&
        Objects.equals(this.printer, infoResponse.printer) &&
        Objects.equals(this.serial, infoResponse.serial) &&
        Objects.equals(this.updateReady, infoResponse.updateReady);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batteryCharging, batteryPercentage, busy, connectionMode, device, portable, printer, serial, updateReady);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoResponse {\n");
    
    sb.append("    batteryCharging: ").append(toIndentedString(batteryCharging)).append("\n");
    sb.append("    batteryPercentage: ").append(toIndentedString(batteryPercentage)).append("\n");
    sb.append("    busy: ").append(toIndentedString(busy)).append("\n");
    sb.append("    connectionMode: ").append(toIndentedString(connectionMode)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    portable: ").append(toIndentedString(portable)).append("\n");
    sb.append("    printer: ").append(toIndentedString(printer)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    updateReady: ").append(toIndentedString(updateReady)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

