/*
 * Kinetic Smart API
 * Kinetic Smart Swagger Implementatin
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.citypay.pos.model.kinetic;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SaleRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-19T12:47:05.325Z")
public class SaleRequest {
  @SerializedName("amount")
  private Integer amount = null;

  @SerializedName("uuid")
  private String uuid = null;

  public SaleRequest amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The amount to process in the lowest denomination and in the base currency of the device. 100 for instance would process the transaction for £1.00
   * @return amount
  **/
  @ApiModelProperty(example = "100", required = true, value = "The amount to process in the lowest denomination and in the base currency of the device. 100 for instance would process the transaction for £1.00")
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public SaleRequest uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Can include a unique identifier (uuid) for this transaction, but if none present a new UUID will be assigned and returned. Note, does not have to be a uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "0600ee0b-69df-4b77-cbb5-8a20962a75ab", value = "Can include a unique identifier (uuid) for this transaction, but if none present a new UUID will be assigned and returned. Note, does not have to be a uuid")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaleRequest saleRequest = (SaleRequest) o;
    return Objects.equals(this.amount, saleRequest.amount) &&
        Objects.equals(this.uuid, saleRequest.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaleRequest {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

