/*
 * Kinetic Smart API
 * Kinetic Smart Swagger Implementatin
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.citypay.pos.model.kinetic;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TransactionResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-19T12:47:05.325Z")
public class TransactionResult {
  @SerializedName("status")
  private String status = null;

  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("description")
  private String description = null;

  public TransactionResult status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Provides a textual status of the transaction
   * @return status
  **/
  @ApiModelProperty(example = "false", value = "Provides a textual status of the transaction")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public TransactionResult success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Determines the status of the transaction  false returns that the transaction is in progress
   * @return success
  **/
  @ApiModelProperty(example = "false", value = "Determines the status of the transaction  false returns that the transaction is in progress")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public TransactionResult description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A string describing the status
   * @return description
  **/
  @ApiModelProperty(value = "A string describing the status")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionResult transactionResult = (TransactionResult) o;
    return Objects.equals(this.status, transactionResult.status) &&
        Objects.equals(this.success, transactionResult.success) &&
        Objects.equals(this.description, transactionResult.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, success, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionResult {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

